name: 'ga4_analytics'
version: '1.0.0'

profile: 'ga4_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ log('Starting dbt run: ' ~ run_started_at, info=True) }}"

on-run-end:
  - "{{ log('Finished dbt run. Models completed: ' ~ results | length, info=True) }}"

models:
  ga4_analytics:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'daily']
      +meta:
        owner: Kyamil
        team: analytics_engineering
        layer: staging
        contains_pii: true
    dimensions:
      +materialized: table
      +schema: dimensions
      +tags: ['dimensions', 'daily', 'core']
      +meta:
        owner: Kyamil
        team: analytics_engineering
        layer: core
        contains_pii: false
    facts:
      +materialized: table
      +schema: facts
      +tags: ['facts', 'daily', 'core']
      +meta:
        owner: Kyamil
        team: analytics_engineering
        layer: core
        contains_pii: false
    marts:
          +materialized: table
          +schema: marts
          +tags: ['marts', 'daily']
          +meta:
            owner: jack
            team: analytics_engineering
            layer: marts
            contains_pii: false

seeds:
  ga4_analytics:
    country_region_mapping:
      +schema: seeds
      +column_types:
        country_name: string
        region: string
        sub_region: string